name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        jvm: '21'
    - name: 'format'
      run: scala-cli fmt . --check
    - name: 'Compile'
      run: scala-cli compile --test project.scala scala/*
    - name: 'Test'
      run: scala-cli test project.scala scala/**/*.solutions.test.scala
    - name: 'Validate cheatsheet'
      run: scala-cli run project.scala cheatsheet
