name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '21']

    steps:
    - uses: actions/checkout@v4
    - uses: VirtusLab/scala-cli-setup@main
      with:
        jvm: '21'
    - name: 'Compile'
      run: scala-cli compile --test project.scala scala/*
